CREATE TABLE Z$INSERTREF
(
  NON_MATCH VARCHAR(20),
  INSERT_REF VARCHAR(20)
);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON Z$INSERTREF TO  SYSDBA WITH GRANT OPTION;
 
INSERT INTO Z$INSERTREF (NON_MATCH, INSERT_REF) VALUES ('NON_MATCH_1', '1');
INSERT INTO Z$INSERTREF (NON_MATCH, INSERT_REF) VALUES ('NON_MATCH_2', '2');
INSERT INTO Z$INSERTREF (NON_MATCH, INSERT_REF) VALUES ('NON_MATCH_3', '3');
