CREATE TABLE FIELD_DETAIL
(
  MASTER INTEGER,
  INDX INTEGER,
  FIELD_NAME VARCHAR(40),
  VALU VARCHAR(1000),
  BASERECORD INTEGER,
  TARGET VARCHAR(100),
  QUERY VARCHAR(100),
  BODY VARCHAR(1000),
  MASTER_FIELDS VARCHAR(1000),
  PK_FIELD_NAME VARCHAR(40),
  NEW_VALUE VARCHAR(1000),
  OLD_VALUE VARCHAR(1000),
  NEW_VALUE_SET INTEGER,
  TARGET_VALUES VARCHAR(256)
);

CREATE INDEX IDX_FIELD_DETAIL1 ON FIELD_DETAIL (MASTER,INDX);
CREATE INDEX IDX_FIELD_DETAIL2 ON FIELD_DETAIL (MASTER,NEW_VALUE_SET,VALU,QUERY,PK_FIELD_NAME);

