
--defaults for tables 

SET GENERATOR Z$PK_GEN TO 1000000100;
SET GENERATOR Z$SERVER_NUMBER TO 12;
SET GENERATOR Z$CONTEXT_SEQ TO 10000;
 
INSERT INTO Z$INSERTREF (NON_MATCH, INSERT_REF) VALUES ('NON_MATCH_1', '1');
INSERT INTO Z$INSERTREF (NON_MATCH, INSERT_REF) VALUES ('NON_MATCH_2', '2');
INSERT INTO Z$INSERTREF (NON_MATCH, INSERT_REF) VALUES ('NON_MATCH_3', '3');


INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('ifblank:Yes','YesNo',0,NULL,NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('No','YesNo',0,'0','No',NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Yes','YesNo',1,'1','Yes',NULL);

INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('ifblank:No','NoYes',0,NULL,NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('No','NoYes',0,'0','No',NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Yes','NoYes',1,'1','Yes',NULL);

INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Saturday','Days',-1,'-1',NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Sunday','Days',0,'0',NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Monday','Days',1,'1',NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Tuesday','Days',2,'2',NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Wednesday','Days',3,'3',NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Thursday','Days',4,'4',NULL,NULL);
INSERT INTO Z$DICTIONARY (NAME,CONTEXT,INDX,VALU,EXTRA,BIN) values ('Friday','Days',5,'5',NULL,NULL);

INSERT INTO Z$USER (NAME,LANDING_PAGE,USER_NAME,PASSWRD) values ('Guest','Home/Guest','Guest','Any');
INSERT INTO Z$USER (NAME,LANDING_PAGE,USER_NAME,PASSWRD) values ('SysAdmin','Home/SysAdmin','sysadmin','changethis');

COMMIT;
